version: '3'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - dockerNetwork

  redis:
    image: redis
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis-data:/data
    networks:
      - dockerNetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - dockerNetwork

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    networks:
      - dockerNetwork

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - dockerNetwork


  # nest-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - REDIS_HOST=redis
  #   ports:
  #     - '${PORT}:${PORT}'
  #     - '${WS_PORT}:${WS_PORT}'
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - dockerNetwork

volumes:
  postgres:
  redis-data:


networks:
  dockerNetwork:
    driver: bridge
